-- =========================================
-- 0022 · Importar respuestas históricas de Taller 2
-- Total = 10. IDEMPOTENTE.
-- =========================================

do $$
declare
  v_taller_id uuid;
  v_taller_title text;
  v_default_created timestamptz := '2026-04-29T18:00:00-05:00';
begin
  select id, title into v_taller_id, v_taller_title
  from public.talleres where n = 2;

  if v_taller_id is null then
    raise exception 'Taller 2 no encontrado.';
  end if;

  insert into public.quiz_responses (
    taller_id, taller_n, taller_title,
    student_name, student_email, student_school,
    answers, score, total, created_at
  )
  select
    v_taller_id, 2, v_taller_title,
    split_part(email, '@', 1),
    lower(email),
    null,
    '[]'::jsonb,
    score,
    10,
    v_default_created
  from (
    select distinct on (lower(email)) email, score
    from (values
      ('daniel10abadi@gmail.com', 3),
      ('eytaneduenas31@gmail.com', 10),
      ('juan.hernandez.dl3on@gmail.com', 10),
      ('karolalmengor4@gmail.com', 8),
      ('manuelsargentq@gmail.com', 9),
      ('eb72167@gmail.com', 10),
      ('visuetecarlos634@gmail.com', 8),
      ('jonathanfl8r20009@gmail.com', 10),
      ('andersonkeilyne@gmail.com', 8),
      ('frankeloymedina312009gg@gmail.com', 10),
      ('gutierrezkobian@gmail.com', 8),
      ('angeledelgadog@gmail.com', 5),
      ('ariasjoseas0@gmail.com', 10),
      ('melizhang000@gmail.com', 10),
      ('carlos0709el@gmail.com', 10),
      ('treyzonmedina@gmail.com', 9),
      ('quinteroabimelecth@gmail.com', 6),
      ('saidarias78@gmail.com', 10),
      ('lc588913@gmail.com', 10),
      ('yerenichiru@gmail.com', 10),
      ('deadregect@gmail.com', 10),
      ('rosemarysanjur9@gmail.com', 10),
      ('enzo.perezd@gmail.com', 8),
      ('nelsonwigui28@gmail.com', 10),
      ('silvia1992domi@gmail.com', 9),
      ('garridodaireth@gmail.com', 10),
      ('yosashyescu19@gmail.com', 10),
      ('alexander.pperez2705@gmail.com', 9),
      ('jacobygreen720@gmail.com', 10),
      ('yatzelgonzalez648@gmail.com', 10),
      ('galindobrandol@gmail.com', 10),
      ('zoiligonzalez23@gmail.com', 10),
      ('derleydawes85@gmail.com', 8),
      ('pkali1510@gmail.com', 9),
      ('yenishernandez637@gmail.com', 10),
      ('ericdrg162@gmail.com', 10),
      ('endercross171@gmail.com', 10),
      ('ale.rdriguez24@gmail.com', 5),
      ('fanuelsheck@gmail.com', 10),
      ('jaenyurielis616@gmail.com', 10),
      ('ricardoballadares231@gmail.com', 10),
      ('joseph.rios.pro@gmail.com', 10),
      ('camanolisseth345@gmail.com', 10),
      ('victorina.dirac05@gmail.com', 10),
      ('lezcanoviviana962@gmail.com', 10),
      ('pneythan835@gmail.com', 10),
      ('rickielgonzalez@gmail.com', 10),
      ('zmai88678@gmail.com', 9),
      ('flaquerocrack@gmail.com', 10),
      ('cruzhillary598@gmail.com', 9),
      ('pinzonlia1@gmail.com', 9),
      ('maryadnnes@gmail.com', 9),
      ('marioarchibold204@gmail.com', 10),
      ('leog50365@gmail.com', 10),
      ('or85467830@gmail.com', 10),
      ('isaacfgonzalezmartinezs@gmail.com', 10),
      ('machucaalexis42@gmail.com', 10),
      ('yairgamarra92@gmail.com', 9),
      ('gabrielpardo0770@gmail.com', 10),
      ('lr7389188@gmail.com', 8),
      ('pro84321@gmail.com', 9),
      ('agucamargo15@gmail.com', 8),
      ('josephdanielmartinz@gmail.com', 10),
      ('stacydegracia05@gmail.com', 10),
      ('benavidesmmaria23@gmail.com', 10),
      ('marktucok@gmail.com', 10),
      ('pedrogonzalez1221.g@gmail.com', 9),
      ('leonel.antoniocorrea30@gmail.com', 10),
      ('ag1836743@gmail.com', 6),
      ('estefanydominguez013@gmail.com', 9),
      ('angela.labrador2207@gmail.com', 8),
      ('bekeraldair2@gmail.com', 10),
      ('santosmalky66@gmail.com', 10),
      ('angelmoran2410@gmail.com', 7),
      ('rodriguezjosuee57@gmail.com', 9),
      ('linethagrazal8@gmail.com', 9),
      ('allison.coneop@gmail.com', 9),
      ('hguerra885@gmail.com', 10),
      ('gonzalezethan597@gmail.com', 8),
      ('keisyceballos2512@gmail.com', 10),
      ('karol.garcia@oteima.ac.pa', 10),
      ('neptuneh3re@gmail.com', 9),
      ('angelgcero507@gmail.com', 10),
      ('luismiguel09aguilar@gmail.com', 10),
      ('anthonybatista2010@gmail.com', 9),
      ('eduinestribi123@gmail.com', 10),
      ('josecristianbrito@gmail.com', 10),
      ('yoladegutierrez@gmail.com', 10),
      ('jr7172008@gmail.com', 10),
      ('magallonnayelis1@gmail.com', 10),
      ('juanmarod16@gmail.com', 8),
      ('correakeisy17@gmail.com', 10),
      ('alinaarcia2025@gmail.com', 10),
      ('luciamelahiguera@gmail.com', 10),
      ('josselineaimeth180610@gmail.com', 10),
      ('j8028521@gmail.com', 9),
      ('fcoerangel@gmail.com', 9),
      ('melissacastillo9870@gmail.com', 8),
      ('javiansanchez6@gmail.com', 10),
      ('ddmore1995@gmail.com', 8),
      ('alisonaneth1005@gmail.com', 9),
      ('abigailfletes0405@gmail.com', 10),
      ('ricardorod034@gmail.com', 10),
      ('camilaisabelperez2@gmail.com', 9),
      ('maste17fenix@gmail.com', 10),
      ('araizmartines627@gmail.com', 10),
      ('deydiscanto0327@gmail.com', 10),
      ('eithantoribiomsv@gmail.com', 9),
      ('anyeline120@gmail.com', 9),
      ('jaircherigo7@gmail.com', 10),
      ('andrewdamiansv@gmail.com', 10),
      ('vitarekevant@gmail.com', 9),
      ('dannye.0617@gmail.com', 9),
      ('samuelaaron100sm@gmail.com', 8),
      ('yariseldaniels@gmail.com', 10),
      ('vargasariabnys@gmail.com', 10),
      ('yinowilson111@gmail.com', 9),
      ('danielasamaniego0511@gmail.com', 9),
      ('nataly.nguerra@gmail.com', 8),
      ('evelynda1018@gmail.com', 9),
      ('chenemilyganuwu@gmail.com', 9),
      ('dayanabenjamin9@gmail.com', 8),
      ('jr0447201@gmail.com', 10),
      ('gb5297692@gmail.com', 10),
      ('mariaballesteros676@gmail.com', 10),
      ('chamierisnel5@gmail.com', 10),
      ('vielsi231@gmail.com', 10),
      ('gaviperez2010@gmail.com', 10),
      ('lakabragonzalez@gmail.com', 10),
      ('agustincastillo50905@gmail.com', 10),
      ('alfredocampo914@gmail.com', 9),
      ('pili312742@gmail.com', 7),
      ('jotadefr.10@gmail.com', 10),
      ('davidflorencioalba@gmail.com', 10),
      ('emanuel.come31@gmail.com', 10),
      ('luizmartinez0220@gmail.com', 10),
      ('dianethcisneros0@gmail.com', 10),
      ('yohalisvalderrama41@gmail.com', 9),
      ('myarizel325@gmail.com', 9),
      ('johelisssss@gmail.com', 10),
      ('lewitmartinez6@gmail.com', 10),
      ('0navasrashel0@gmail.com', 8),
      ('rubenvazkes08@gmail.com', 8),
      ('daibelysariadnev@gmail.com', 8),
      ('castilloossiris1@gmail.com', 10),
      ('alejandromj0309@gmail.com', 10),
      ('carloseps122@gmail.com', 10),
      ('ortegakarina2308@gmail.com', 10),
      ('delgadoilckany39@gmail.com', 6),
      ('pittinatasha4@gmail.com', 5),
      ('virginia.romero2626@gmail.com', 8),
      ('rashelnavas3@gmail.com', 10),
      ('jesucitomariano11@gmail.com', 9),
      ('jesusegonzalesr@gmail.com', 10),
      ('d85106238@gmail.com', 9),
      ('mariangeldelcid12@gmail.com', 10),
      ('andrealba2423@gmail.com', 10),
      ('barrosoilimeyjulieth@gmail.com', 8),
      ('fredyaldaircastro@gmail.com', 10),
      ('angela01delcid@gmail.com', 10),
      ('gutierrezjosuet137@gmail.com', 8),
      ('sanchezsabinaesther.13@gmail.com', 10),
      ('jesuselia7709@gmail.com', 4),
      ('lilibethcastillo581@gmail.com', 9),
      ('lilibethatencio95@gmail.com', 10),
      ('lmosquera015@gmail.com', 10),
      ('eg1034562@gmail.com', 10),
      ('emirdeleonpanama@gmail.com', 9),
      ('emelidaflores509@gmail.com', 9),
      ('jasthsoto88@gmail.com', 10),
      ('sergiotunon2@gmail.com', 10),
      ('dareniespinosa5@gmail.com', 10),
      ('adoniotorres08@gmail.com', 10),
      ('sader2373@gmail.com', 8),
      ('cedenoyair6@gmail.com', 10),
      ('deleonmariadesolis@gmail.com', 10),
      ('lramosykes20@gmail.com', 10),
      ('denisevgvg03@gmail.com', 9),
      ('jackie125134@gmail.com', 10),
      ('jafetdrakes@gmail.com', 10),
      ('adejesusaucedo@gmail.com', 9),
      ('erasmoarauz09@gmail.com', 10),
      ('castilloluisma23@gmail.com', 9),
      ('proposito2340@gmail.com', 10),
      ('robertochonngg@gmail.com', 10),
      ('melanync020@gmail.com', 8),
      ('hidalgoernesto318@gmail.com', 9),
      ('gpetana10@gmail.com', 10),
      ('asbelcanto91@gmail.com', 10),
      ('luciaaduenas31@gmail.com', 10),
      ('cordobaanna63@gmail.com', 9),
      ('serviciosbonillamorales@gmail.com', 10),
      ('robertoellis3001@gmail.com', 10),
      ('obareth2008@gmail.com', 10),
      ('joseluisra233@gmail.com', 10),
      ('almengorabel953@gmail.com', 10),
      ('geraldaustin06@gmail.com', 10),
      ('perikaperez163@gmail.com', 10),
      ('rubencinperez2008@gmail.com', 10),
      ('alabarcayojanis@gmail.com', 10),
      ('yohanalibrada@gmail.com', 7),
      ('john.diaz.2707@gmail.com', 10),
      ('jasielrobles27@gmail.com', 10),
      ('liatnethtunon01@gmail.com', 8),
      ('jeansucre1231@gmail.com', 10),
      ('dasyrfernandez62@gmail.com', 9),
      ('love.riri0709@gmail.com', 10),
      ('f82814970@gmail.com', 9),
      ('victoria.batista.q.00@gmail.com', 9),
      ('jahirgonzalez817@gmail.com', 10),
      ('pabloen0330@gmail.com', 10),
      ('contranueva129@gmail.com', 10),
      ('jaelmisael1010@gmail.com', 9),
      ('miguel.hooker02@gmail.com', 7),
      ('angeluistenorio05@gmail.com', 10),
      ('kayleesophia12@gmail.com', 10),
      ('marinajime134@gmail.com', 10),
      ('cristhianquintana209@gmail.com', 10),
      ('franklinvas28@gmail.com', 10),
      ('bnikeydis@gmail.com', 10),
      ('victoriataysha36@gmail.com', 9),
      ('kenilethpalacio3@gmail.com', 10),
      ('david12david12@gmail.com', 9),
      ('camandonagiovanniemilio@gmail.com', 10),
      ('carolecp28@gmail.com', 10),
      ('omar.chicken.23@gmail.com', 10),
      ('urriolawaga770@gmail.com', 8),
      ('fabregalucas@gmail.com', 10),
      ('pablomagallon570@gmail.com', 10),
      ('bryanpres19@gmail.com', 8)
    ) as t(email, score)
    order by lower(email), score desc
  ) deduped
  on conflict (taller_id, student_email) do update
    set score = greatest(quiz_responses.score, excluded.score);

  raise notice 'Importación Taller 2 completada.';
end $$;
